# Generated by Django 4.0.4 on 2022-04-24 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uworldapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'verbose_name_plural': 'Performance'},
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='uworldapp.performance'),
            preserve_default=False,
        ),
    ]
