# Generated by Django 4.0.4 on 2022-04-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uworldapp', '0004_alter_player_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophee', models.CharField(default='no trophee', max_length=100)),
                ('year', models.DateField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'verbose_name_plural': 'Performance'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name_plural': 'Player'},
        ),
        migrations.AddField(
            model_name='player',
            name='trophy',
            field=models.ManyToManyField(to='uworldapp.trophees'),
        ),
    ]
