# Generated by Django 4.0.4 on 2022-04-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uworldapp', '0006_alter_trophees_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='uworldapp.performance'),
        ),
    ]
